# crs
crs:
  proj: 8059 # for projected
  decdeg: 4326 # for decimal degrees
# env context
env:
  aoi:
    vector: sa_br_dissolve
    filt_col: NULL
    filt_level: NULL
    vec_buffer: 0
  grain:
    temp: "P10Y"
    res: 90
